### ISSUE TITLE
hash keys as strings cannot retrieve respective value

### ISSUE THREAD

**Issue by bnisbett** [timlinquist/simple_eav#13]
One other thing i discovered was that if a user inputs the custom attributes with the key as a string then simple_eav  does not retrieve the value for that key.
For example:

```
@post = Post.create("intro" => "I am an intro")

@post.intro #NoMethodError: undefined method `intro' for #<Post:0x00000100e45060>
```

 The fix i did was to make all keys symbols when they are saved. So I changed this line in the assign_attributes() method.

```
simple_eav_attrs[column] = value
```

to 

```
simple_eav_attrs[column.to_sym] = value
```

Not sure if this is the approach you would take but this is just my suggestion. 
This however is not an issue if submitting the custom attributes through a form since rails saves the serialized attributes as a HashWithIndifferentAccess.

**Comment by timlinquist** [comment]
Ah I must have overlooked that. I'll add that back in or just use HashWithIndifferentAccess internally rather than a hash.

**Comment by bnisbett** [comment]
HashWithIndifferentAccess internally would be best I guess. That way regardless of the custom attribute being created through the form or the console the type will be the same as opposed to having some as plain Hash and some as HashWithIndifferentAccess
