### ISSUE TITLE
Stack level too deep error with Simple EAV + Factory Girl (1.3.3)

### ISSUE THREAD

**Issue by rwilcox** [timlinquist/simple_eav#5]
I don't have time to give you a proper test case, but here's what I'm seeing:

Technologies:
1. I included simple eav into a model (my user model).
2. I use Factory Girl to generate test data

Issue:

I get a "stack level too deep" errors when I try to run my specs, particularly constructing a user:

```
 user = Factory.create(:user)
```

My user factory definition looks like:

```
Factory.define :user do |u|
u.email         { Factory.next(:email) }
u.identifier    { Factory.next(:magic_user_identifier) }
u.name          "John Doe"
u.admin         false
u.enabled   true
end
```

I'm running the released SimpleEAV (0.1.0)

I can't produce more of a simple right now (gotta ship this app), but this report is as much of a reminder to myself to get this done, as it is to report the issue to you.

**Comment by timlinquist** [comment]
I'll start a sample project with factory girl 1.3.3.  What version of ActiveRecord are you seeing this on?

**Comment by timlinquist** [comment]
Also are you using Rails?

**Comment by timlinquist** [comment]
I was able to reproduce this with: factory_girl, 1.3.3, rspec, 2.6.0, active_record, 3.0.9, and simpe_eav, 0.1.0.  I'll try to debug the source of the error.  If it turns out to be a bug in factory_girl I'll forward it to them.

**Comment by timlinquist** [comment]
Tested & verified in this gem's specs.  Also verified in sample app using factory_girl.  See latest commits for details. 
Upgrade to 0.2.0 and you should be good to go.

Thanks for catching this small oversight. I don't know how I missed it myself.

**Comment by rwilcox** [comment]
WOW, awesome! Thank you very much!! (Rails 3.0.9 was what I was using, so it looks like your fix should work :) )
