### ISSUE TITLE
fatal error on multiple servers

### ISSUE THREAD

**Issue by amcox** [timlinquist/simple_eav#6]
The 'include SimpleEav' is terminating the rails server, whether I use WEBbrick, Thin, or Unicorn.

From Thin, I get a ton of lines in the log, all saying this over and over:

/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:55:in `method_missing'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:24:in`simple_eav_attributes'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:55:in `method_missing'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:24:in`simple_eav_attributes'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:55:in `method_missing'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:24:in`simple_eav_attributes'
/usr/local/lib/ruby/gems/1.9.1/gems/simple_eav-0.2.0/lib/simple_eav.rb:0:in `method_missing'

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6

Webbrick just dies with an unhelpful message.

I don't have the chops to dig in, but hopefully finding a server that outputted some kind of information was helpful.

**Comment by timlinquist** [comment]
Ooooooh. This will be a fun one.  I'm headed to http://cascadiarubyconf.com/ today so it may be a bit before I get to this.

**Comment by amerine** [comment]
@amcox While Tim is looking for a solution can you verify that you've added and specified the column with the `configure_simple_eav` call?

**Comment by amcox** [comment]
I have added the specific column:

``` ruby
create_table "users", :force => true do |t|
    t.string   "username"
    t.string   "first_name"
    t.string   "last_name"
   ...
    t.text     "requirements"
  end
```

And I call the setup:

``` ruby
class User < ActiveRecord::Base

  include SimpleEav

  configure_simple_eav :requirements # This sets up the serialization for your custom attributes

  devise :database_authenticatable
```

The gem seems to work fine in the console. I can get and set attributes through the :requirements column just fine.

But whenever I try to load a page that uses the "users" controller, the server bites the dust. Even the index page, which makes no calls to the simple_eav methods, crashes.

**Comment by timlinquist** [comment]
This bug should be fixed with the commit above.   A new version has been pushed. 

Please verify for me.

**Comment by amcox** [comment]
Awesome.

It looks like it's working here as well.

And definitely let me know if there was a place where I should have been looking to figure tout what was going on.

Thanks for the hard work on your vacation.
