### ISSUE TITLE
Specs fail under Rails 3.1

### ISSUE THREAD

**Issue by rwilcox** [timlinquist/simple_eav#9]
I ran `rspec spec` and got the following errors:

```
rspec ./spec/lib/simple_eav_spec.rb:72 # SimpleEav Expected ActiveRecord behavior nested attributes nests the attributes properly
rspec ./spec/lib/simple_eav_spec.rb:91 # SimpleEav Expected ActiveRecord behavior given a hash of undefined attributes creates a person with a name
rspec ./spec/lib/simple_eav_spec.rb:95 # SimpleEav Expected ActiveRecord behavior given a hash of undefined attributes saves the person's name
rspec ./spec/lib/simple_eav_spec.rb:101 # SimpleEav Expected ActiveRecord behavior given a hash of undefined attributes updates the person's name
rspec ./spec/lib/simple_eav_spec.rb:106 # SimpleEav Expected ActiveRecord behavior given a hash of undefined attributes initializes the person with a name
rspec ./spec/lib/simple_eav_spec.rb:119 # SimpleEav Expected ActiveRecord behavior given a hash of defined attributes does not set the age in the simple eav attributes
rspec ./spec/lib/simple_eav_spec.rb:174 # SimpleEav Adding an attribute with existing attributes updates the attributes without removing the old
```

This happened both in 1.8.7 and 1.9.2. Again, this is half reminder to myself to do figure out what's going on and make the specs pass, but it's more work than I bargained on doing just right now.

**Comment by timlinquist** [comment]
All tests are passing locally for me on 1.8.7p229,330, 1.9.1pxxx, and 1.9.2pxxx.  

Can you provide me the following in a gist?  

which ruby
cd into your simple_eav fork
- bundle exec gem list
  rvm info

**Comment by rwilcox** [comment]
After some better investigations, here's what I get:

Ruby 1.9.2 / Rails 3.1: FAIL
Ruby 1.8.7, Rails 3.1:  FAIL

Ruby 1.9.2, Rails 3.0:  PASS
Ruby 1.8.7, Rails 3.0:  PASS

I must have been sloppy earlier, when I reported the specs failed - I thought they failed in Rails 3.0. Obviously not, because more careful work shows it's just Rails 3.1 that's the issue

**Comment by timlinquist** [comment]
Ok.  I just got this up on travis-ci.org.  I'll start testing on 3.1 soon.

**Comment by timlinquist** [comment]
I have really neglected this.  I am making it my focus to at least get you an answer this week on the issue(s).

**Comment by timlinquist** [comment]
This really took me a long time to knock out. You can gem install simple_eav -v 1.0.0 for Rails 3.1 compatibility now.
